# Generated by Django 3.2.22 on 2023-11-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20231109_2134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Movie',
        ),
    ]
