# Generated by Django 3.2.22 on 2023-11-11 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_rename_booking_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='booking_email',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='booking_username',
        ),
        migrations.AddField(
            model_name='seat',
            name='booking_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_num',
            field=models.CharField(max_length=5),
        ),
    ]
