# Generated by Django 3.2.22 on 2023-11-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='Some default description'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Default genre', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='PG', max_length=5),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(default='https://www.example.com/default_trailer'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
